# Header
menu:
  Home: /
  Archives: /archive
  Impressum: /impressum
#  Github:
 #   url: https://github.com/klugjo/hexo-theme-clean-blog
  #  icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: #Configurable Title

# URL of the Home page image
#index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg
index_cover: img/blog_logo.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-34726227-1

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/fabsenet
twitter_handle: fabsenet
facebook_url: https://facebook.com/fabsenet
github_url: https://github.com/fabsenet
mailto: fabse@fabse.net